diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),

]

private_diary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('accounts/', include('allauth.urls/'))
]

accounts/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

diary/models.py
from django.db import models

# Create your models here.

diary/forms.py
import os

from django import forms
from django.core.mail import EmailMessage


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください'

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'ここにメッセージを入力してください'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ{}'.format(title)
        message = '送信者名: {0}\nメールアドレス:{1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = os.environ.get('FROM_EMAIL')
        to_list = [
            os.environ.get('FROM_EMAIL')
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

accounts/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
import logging

from django.urls import reverse_lazy

from django.views import generic
from.forms import InquiryForm

from django.contrib import messages

logger = logging.getLogger(__name__)

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('diary:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

diary/templates/base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=0">
    <meta name="discription" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'asset/favicon.ico' %}" />

    <!--  Font Awesome icons(free version)  -->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!--  Google fonts   -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,,400i,700,700i,900,900i" rel="stylesheet" />

    <!--  Core theme CSS (includes Bootstarap)  -->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet"/>

    <!--  My style  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}

</head>
<body>
    <div id="wrapper">
        <!--   Navigation     -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-taeget="#navbarResponsive" aria-controls="navbarResponsive"
                        aria-expanded="false" aria-label="Toggele navigation">
                    <span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link {% block active_inquiry %}{% endblock %}"
                               href="{% url 'diary:inquiry' %}">INQUIRY</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% block active_signup %}{% endblock %}"
                               href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% block active_login %}{% endblock%}"
                               href="{% url 'account_login' %}">Log In</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block header%}{% endblock%}


        {% if messages %}
        <div class ="container my-div-style">
            <div class="row">
                <ul class="messages" style="list-style: none;">
                    {% for message in messages %}
                    <li {% if message.tags　%} class="{{ message.tags }}" {% endif　%}>
                        {{ message }}
                    </li>
                    {% endfor%}
                </ul>
            </div>
        </div>

        {% endif%}

        {% block contents%}{% endblock%}

    <!--    Footer    -->
        <footer class="py-5 bg-black">
            <div class="container px-5">
                <p class="m-0 text-center text-white small">
                    Copyright &copy; PrivateDiary 2022
                </p>
            </div>
        </footer>

    <!--   Bootstrap core js     -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    </div>

</body>
</html>

diary/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}web上にあなた専用の日記ページを保存できるサービス|Private Diary{% endblock %}

{% block header %}

<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0">Private Diary</h1>
            <h2 class="masthead-subheading mb-0">あなた専用の日記保存サービス</h2>
            <a href="{% irl 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/01.jpg'%}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Web Diary</h2>
                    <p>Web上で作成/編集/削除ができる日記</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg'%}" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">Save Your Diary</h2>
                    <p>あなたの日記をWebに保存</p>
                </div>
            </div>
        </div>
    </div>

</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static　'assets/img/03.jpg'%}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Membership System</h2>
                    <p>会員制のWeb日記サービス</p>
                </div>
            </div>
        </div>
    </div>

</section>
{% endblock %}

diary/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
  <div class="my-div-style">
    <form method="post">
      {% csrf_token %}

      {{ form.non_field_errors }}

      {% for field in form %}
      <div class="mb-4 col-8">
        <label for="{{ field.id_for_label }}" class="form-label">
          <strong>{{ field.label_tag }}</strong>
        </label>
        {{ field }}
        {{ field.errors }}
      </div>
      {% endfor %}
      <button class="btn btn-primary" type="submit">送信</button>
    </form>
  </div>
</div>
{% endblock %}